name: canokey-management-tool

on:
  push:
    branches:    
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: git clone https://github.com/canokeys/canokey-management-tool
    - run: cd canokey-management-tool && flutter pub get
    - run: cd canokey-management-tool && flutter build web

    - name: Archive code coverage results #上传build文件
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: ${{ github.workspace }}/canokey-management-tool/build/web*

    - name: Deploy #部署到web分支
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: web
        FOLDER: ${{ github.workspace }}/canokey-management-tool/build/web
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
